### ISSUE TITLE
Issue with both files.

### ISSUE THREAD

**Issue by k4benz** [agroden/2nAssignment#1]
Issue at line 34 of the file 2n.py, see error below

print 'code for "%s" ends with more than %d zeros, adding "010"' % (old_key[0], n)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?

Issue at line 40 of the file htree.py, see error below

    print '{}{}'.format(prefix, key)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?

**Comment by agroden** [comment]
Really, my dude? The first issue you open is for print statements in a repo made for homework that is almost as old as your account? lol

This was written for Python 2.7 8 years ago, I'm not surprised it doesn't work with modern Python. As for how to get it working in 2022, I'll leave it as an exercise to the reader - I'm certain with a little effort you'll be able to get it working in Python 3+, there have only been a few breaking changes that really affect this project.

That being said, thank you for reminding me to archive this.
